'use strict';
// Source: Google Ads geo targets CSV (2026-05-28) cross-referenced with
// Kevel /v1/countries API. DMA_REGION entries are not included — see
// assumption notes at top of translateGeoTargeting.js.

const GEO_TARGET_MAP = {
  // --- COUNTRIES (219 active entries from Google geo targets CSV 2026-05-28) ---
  2004: { CountryCode: "AF", type: "Country", displayName: "Afghanistan" },
  2008: { CountryCode: "AL", type: "Country", displayName: "Albania" },
  2010: { CountryCode: "AQ", type: "Country", displayName: "Antarctica" },
  2012: { CountryCode: "DZ", type: "Country", displayName: "Algeria" },
  2016: { CountryCode: "AS", type: "Country", displayName: "American Samoa" },
  2020: { CountryCode: "AD", type: "Country", displayName: "Andorra" },
  2024: { CountryCode: "AO", type: "Country", displayName: "Angola" },
  2028: { CountryCode: "AG", type: "Country", displayName: "Antigua and Barbuda" },
  2031: { CountryCode: "AZ", type: "Country", displayName: "Azerbaijan" },
  2032: { CountryCode: "AR", type: "Country", displayName: "Argentina" },
  2036: { CountryCode: "AU", type: "Country", displayName: "Australia" },
  2040: { CountryCode: "AT", type: "Country", displayName: "Austria" },
  2044: { CountryCode: "BS", type: "Country", displayName: "The Bahamas" },
  2048: { CountryCode: "BH", type: "Country", displayName: "Bahrain" },
  2050: { CountryCode: "BD", type: "Country", displayName: "Bangladesh" },
  2051: { CountryCode: "AM", type: "Country", displayName: "Armenia" },
  2052: { CountryCode: "BB", type: "Country", displayName: "Barbados" },
  2056: { CountryCode: "BE", type: "Country", displayName: "Belgium" },
  2064: { CountryCode: "BT", type: "Country", displayName: "Bhutan" },
  2068: { CountryCode: "BO", type: "Country", displayName: "Bolivia" },
  2070: { CountryCode: "BA", type: "Country", displayName: "Bosnia and Herzegovina" },
  2072: { CountryCode: "BW", type: "Country", displayName: "Botswana" },
  2076: { CountryCode: "BR", type: "Country", displayName: "Brazil" },
  2084: { CountryCode: "BZ", type: "Country", displayName: "Belize" },
  2090: { CountryCode: "SB", type: "Country", displayName: "Solomon Islands" },
  2096: { CountryCode: "BN", type: "Country", displayName: "Brunei" },
  2100: { CountryCode: "BG", type: "Country", displayName: "Bulgaria" },
  2104: { CountryCode: "MM", type: "Country", displayName: "Myanmar (Burma)" },
  2108: { CountryCode: "BI", type: "Country", displayName: "Burundi" },
  2112: { CountryCode: "BY", type: "Country", displayName: "Belarus" },
  2116: { CountryCode: "KH", type: "Country", displayName: "Cambodia" },
  2120: { CountryCode: "CM", type: "Country", displayName: "Cameroon" },
  2124: { CountryCode: "CA", type: "Country", displayName: "Canada" },
  2132: { CountryCode: "CV", type: "Country", displayName: "Cabo Verde" },
  2140: { CountryCode: "CF", type: "Country", displayName: "Central African Republic" },
  2144: { CountryCode: "LK", type: "Country", displayName: "Sri Lanka" },
  2148: { CountryCode: "TD", type: "Country", displayName: "Chad" },
  2152: { CountryCode: "CL", type: "Country", displayName: "Chile" },
  2156: { CountryCode: "CN", type: "Country", displayName: "China" },
  2162: { CountryCode: "CX", type: "Country", displayName: "Christmas Island" },
  2166: { CountryCode: "CC", type: "Country", displayName: "Cocos (Keeling) Islands" },
  2170: { CountryCode: "CO", type: "Country", displayName: "Colombia" },
  2174: { CountryCode: "KM", type: "Country", displayName: "Comoros" },
  2178: { CountryCode: "CG", type: "Country", displayName: "Republic of the Congo" },
  2180: { CountryCode: "CD", type: "Country", displayName: "Democratic Republic of the Congo" },
  2184: { CountryCode: "CK", type: "Country", displayName: "Cook Islands" },
  2188: { CountryCode: "CR", type: "Country", displayName: "Costa Rica" },
  2191: { CountryCode: "HR", type: "Country", displayName: "Croatia" },
  2196: { CountryCode: "CY", type: "Country", displayName: "Cyprus" },
  2203: { CountryCode: "CZ", type: "Country", displayName: "Czechia" },
  2204: { CountryCode: "BJ", type: "Country", displayName: "Benin" },
  2208: { CountryCode: "DK", type: "Country", displayName: "Denmark" },
  2212: { CountryCode: "DM", type: "Country", displayName: "Dominica" },
  2214: { CountryCode: "DO", type: "Country", displayName: "Dominican Republic" },
  2218: { CountryCode: "EC", type: "Country", displayName: "Ecuador" },
  2222: { CountryCode: "SV", type: "Country", displayName: "El Salvador" },
  2226: { CountryCode: "GQ", type: "Country", displayName: "Equatorial Guinea" },
  2231: { CountryCode: "ET", type: "Country", displayName: "Ethiopia" },
  2232: { CountryCode: "ER", type: "Country", displayName: "Eritrea" },
  2233: { CountryCode: "EE", type: "Country", displayName: "Estonia" },
  2239: { CountryCode: "GS", type: "Country", displayName: "South Georgia and the South Sandwich Islands" },
  2242: { CountryCode: "FJ", type: "Country", displayName: "Fiji" },
  2246: { CountryCode: "FI", type: "Country", displayName: "Finland" },
  2250: { CountryCode: "FR", type: "Country", displayName: "France" },
  2258: { CountryCode: "PF", type: "Country", displayName: "French Polynesia" },
  2260: { CountryCode: "TF", type: "Country", displayName: "French Southern and Antarctic Lands" },
  2262: { CountryCode: "DJ", type: "Country", displayName: "Djibouti" },
  2266: { CountryCode: "GA", type: "Country", displayName: "Gabon" },
  2268: { CountryCode: "GE", type: "Country", displayName: "Georgia" },
  2270: { CountryCode: "GM", type: "Country", displayName: "The Gambia" },
  2276: { CountryCode: "DE", type: "Country", displayName: "Germany" },
  2288: { CountryCode: "GH", type: "Country", displayName: "Ghana" },
  2296: { CountryCode: "KI", type: "Country", displayName: "Kiribati" },
  2300: { CountryCode: "GR", type: "Country", displayName: "Greece" },
  2308: { CountryCode: "GD", type: "Country", displayName: "Grenada" },
  2316: { CountryCode: "GU", type: "Country", displayName: "Guam" },
  2320: { CountryCode: "GT", type: "Country", displayName: "Guatemala" },
  2324: { CountryCode: "GN", type: "Country", displayName: "Guinea" },
  2328: { CountryCode: "GY", type: "Country", displayName: "Guyana" },
  2332: { CountryCode: "HT", type: "Country", displayName: "Haiti" },
  2334: { CountryCode: "HM", type: "Country", displayName: "Heard Island and McDonald Islands" },
  2336: { CountryCode: "VA", type: "Country", displayName: "Vatican City" },
  2340: { CountryCode: "HN", type: "Country", displayName: "Honduras" },
  2348: { CountryCode: "HU", type: "Country", displayName: "Hungary" },
  2352: { CountryCode: "IS", type: "Country", displayName: "Iceland" },
  2356: { CountryCode: "IN", type: "Country", displayName: "India" },
  2360: { CountryCode: "ID", type: "Country", displayName: "Indonesia" },
  2368: { CountryCode: "IQ", type: "Country", displayName: "Iraq" },
  2372: { CountryCode: "IE", type: "Country", displayName: "Ireland" },
  2376: { CountryCode: "IL", type: "Country", displayName: "Israel" },
  2380: { CountryCode: "IT", type: "Country", displayName: "Italy" },
  2384: { CountryCode: "CI", type: "Country", displayName: "Cote d'Ivoire" },
  2388: { CountryCode: "JM", type: "Country", displayName: "Jamaica" },
  2392: { CountryCode: "JP", type: "Country", displayName: "Japan" },
  2398: { CountryCode: "KZ", type: "Country", displayName: "Kazakhstan" },
  2400: { CountryCode: "JO", type: "Country", displayName: "Jordan" },
  2404: { CountryCode: "KE", type: "Country", displayName: "Kenya" },
  2410: { CountryCode: "KR", type: "Country", displayName: "South Korea" },
  2414: { CountryCode: "KW", type: "Country", displayName: "Kuwait" },
  2417: { CountryCode: "KG", type: "Country", displayName: "Kyrgyzstan" },
  2418: { CountryCode: "LA", type: "Country", displayName: "Laos" },
  2422: { CountryCode: "LB", type: "Country", displayName: "Lebanon" },
  2426: { CountryCode: "LS", type: "Country", displayName: "Lesotho" },
  2428: { CountryCode: "LV", type: "Country", displayName: "Latvia" },
  2430: { CountryCode: "LR", type: "Country", displayName: "Liberia" },
  2434: { CountryCode: "LY", type: "Country", displayName: "Libya" },
  2438: { CountryCode: "LI", type: "Country", displayName: "Liechtenstein" },
  2440: { CountryCode: "LT", type: "Country", displayName: "Lithuania" },
  2442: { CountryCode: "LU", type: "Country", displayName: "Luxembourg" },
  2450: { CountryCode: "MG", type: "Country", displayName: "Madagascar" },
  2454: { CountryCode: "MW", type: "Country", displayName: "Malawi" },
  2458: { CountryCode: "MY", type: "Country", displayName: "Malaysia" },
  2462: { CountryCode: "MV", type: "Country", displayName: "Maldives" },
  2466: { CountryCode: "ML", type: "Country", displayName: "Mali" },
  2470: { CountryCode: "MT", type: "Country", displayName: "Malta" },
  2478: { CountryCode: "MR", type: "Country", displayName: "Mauritania" },
  2480: { CountryCode: "MU", type: "Country", displayName: "Mauritius" },
  2484: { CountryCode: "MX", type: "Country", displayName: "Mexico" },
  2492: { CountryCode: "MC", type: "Country", displayName: "Monaco" },
  2496: { CountryCode: "MN", type: "Country", displayName: "Mongolia" },
  2498: { CountryCode: "MD", type: "Country", displayName: "Moldova" },
  2499: { CountryCode: "ME", type: "Country", displayName: "Montenegro" },
  2504: { CountryCode: "MA", type: "Country", displayName: "Morocco" },
  2508: { CountryCode: "MZ", type: "Country", displayName: "Mozambique" },
  2512: { CountryCode: "OM", type: "Country", displayName: "Oman" },
  2516: { CountryCode: "NA", type: "Country", displayName: "Namibia" },
  2520: { CountryCode: "NR", type: "Country", displayName: "Nauru" },
  2524: { CountryCode: "NP", type: "Country", displayName: "Nepal" },
  2528: { CountryCode: "NL", type: "Country", displayName: "Netherlands" },
  2531: { CountryCode: "CW", type: "Country", displayName: "Curacao" },
  2534: { CountryCode: "SX", type: "Country", displayName: "Sint Maarten" },
  2535: { CountryCode: "BQ", type: "Country", displayName: "Caribbean Netherlands" },
  2540: { CountryCode: "NC", type: "Country", displayName: "New Caledonia" },
  2548: { CountryCode: "VU", type: "Country", displayName: "Vanuatu" },
  2554: { CountryCode: "NZ", type: "Country", displayName: "New Zealand" },
  2558: { CountryCode: "NI", type: "Country", displayName: "Nicaragua" },
  2562: { CountryCode: "NE", type: "Country", displayName: "Niger" },
  2566: { CountryCode: "NG", type: "Country", displayName: "Nigeria" },
  2570: { CountryCode: "NU", type: "Country", displayName: "Niue" },
  2574: { CountryCode: "NF", type: "Country", displayName: "Norfolk Island" },
  2578: { CountryCode: "NO", type: "Country", displayName: "Norway" },
  2580: { CountryCode: "MP", type: "Country", displayName: "Northern Mariana Islands" },
  2581: { CountryCode: "UM", type: "Country", displayName: "United States Minor Outlying Islands" },
  2583: { CountryCode: "FM", type: "Country", displayName: "Micronesia" },
  2584: { CountryCode: "MH", type: "Country", displayName: "Marshall Islands" },
  2585: { CountryCode: "PW", type: "Country", displayName: "Palau" },
  2586: { CountryCode: "PK", type: "Country", displayName: "Pakistan" },
  2591: { CountryCode: "PA", type: "Country", displayName: "Panama" },
  2598: { CountryCode: "PG", type: "Country", displayName: "Papua New Guinea" },
  2600: { CountryCode: "PY", type: "Country", displayName: "Paraguay" },
  2604: { CountryCode: "PE", type: "Country", displayName: "Peru" },
  2608: { CountryCode: "PH", type: "Country", displayName: "Philippines" },
  2612: { CountryCode: "PN", type: "Country", displayName: "Pitcairn Islands" },
  2616: { CountryCode: "PL", type: "Country", displayName: "Poland" },
  2620: { CountryCode: "PT", type: "Country", displayName: "Portugal" },
  2624: { CountryCode: "GW", type: "Country", displayName: "Guinea-Bissau" },
  2626: { CountryCode: "TL", type: "Country", displayName: "Timor-Leste" },
  2634: { CountryCode: "QA", type: "Country", displayName: "Qatar" },
  2642: { CountryCode: "RO", type: "Country", displayName: "Romania" },
  2643: { CountryCode: "RU", type: "Country", displayName: "Russia" },
  2646: { CountryCode: "RW", type: "Country", displayName: "Rwanda" },
  2652: { CountryCode: "BL", type: "Country", displayName: "Saint Barthelemy" },
  2654: { CountryCode: "SH", type: "Country", displayName: "Saint Helena, Ascension and Tristan da Cunha" },
  2659: { CountryCode: "KN", type: "Country", displayName: "Saint Kitts and Nevis" },
  2662: { CountryCode: "LC", type: "Country", displayName: "Saint Lucia" },
  2663: { CountryCode: "MF", type: "Country", displayName: "Saint Martin" },
  2666: { CountryCode: "PM", type: "Country", displayName: "Saint Pierre and Miquelon" },
  2670: { CountryCode: "VC", type: "Country", displayName: "Saint Vincent and the Grenadines" },
  2674: { CountryCode: "SM", type: "Country", displayName: "San Marino" },
  2678: { CountryCode: "ST", type: "Country", displayName: "Sao Tome and Principe" },
  2682: { CountryCode: "SA", type: "Country", displayName: "Saudi Arabia" },
  2686: { CountryCode: "SN", type: "Country", displayName: "Senegal" },
  2688: { CountryCode: "RS", type: "Country", displayName: "Serbia" },
  2690: { CountryCode: "SC", type: "Country", displayName: "Seychelles" },
  2694: { CountryCode: "SL", type: "Country", displayName: "Sierra Leone" },
  2702: { CountryCode: "SG", type: "Country", displayName: "Singapore" },
  2703: { CountryCode: "SK", type: "Country", displayName: "Slovakia" },
  2704: { CountryCode: "VN", type: "Country", displayName: "Vietnam" },
  2705: { CountryCode: "SI", type: "Country", displayName: "Slovenia" },
  2706: { CountryCode: "SO", type: "Country", displayName: "Somalia" },
  2710: { CountryCode: "ZA", type: "Country", displayName: "South Africa" },
  2716: { CountryCode: "ZW", type: "Country", displayName: "Zimbabwe" },
  2724: { CountryCode: "ES", type: "Country", displayName: "Spain" },
  2728: { CountryCode: "SS", type: "Country", displayName: "South Sudan" },
  2736: { CountryCode: "SD", type: "Country", displayName: "Sudan" },
  2740: { CountryCode: "SR", type: "Country", displayName: "Suriname" },
  2748: { CountryCode: "SZ", type: "Country", displayName: "Eswatini" },
  2752: { CountryCode: "SE", type: "Country", displayName: "Sweden" },
  2756: { CountryCode: "CH", type: "Country", displayName: "Switzerland" },
  2760: { CountryCode: "SY", type: "Country", displayName: "Syria" },
  2762: { CountryCode: "TJ", type: "Country", displayName: "Tajikistan" },
  2764: { CountryCode: "TH", type: "Country", displayName: "Thailand" },
  2768: { CountryCode: "TG", type: "Country", displayName: "Togo" },
  2772: { CountryCode: "TK", type: "Country", displayName: "Tokelau" },
  2776: { CountryCode: "TO", type: "Country", displayName: "Tonga" },
  2780: { CountryCode: "TT", type: "Country", displayName: "Trinidad and Tobago" },
  2784: { CountryCode: "AE", type: "Country", displayName: "United Arab Emirates" },
  2788: { CountryCode: "TN", type: "Country", displayName: "Tunisia" },
  2792: { CountryCode: "TR", type: "Country", displayName: "Turkiye" },
  2795: { CountryCode: "TM", type: "Country", displayName: "Turkmenistan" },
  2798: { CountryCode: "TV", type: "Country", displayName: "Tuvalu" },
  2800: { CountryCode: "UG", type: "Country", displayName: "Uganda" },
  2804: { CountryCode: "UA", type: "Country", displayName: "Ukraine" },
  2807: { CountryCode: "MK", type: "Country", displayName: "North Macedonia" },
  2818: { CountryCode: "EG", type: "Country", displayName: "Egypt" },
  2826: { CountryCode: "GB", type: "Country", displayName: "United Kingdom" },
  2831: { CountryCode: "GG", type: "Country", displayName: "Guernsey" },
  2832: { CountryCode: "JE", type: "Country", displayName: "Jersey" },
  2833: { CountryCode: "IM", type: "Country", displayName: "Isle of Man" },
  2834: { CountryCode: "TZ", type: "Country", displayName: "Tanzania" },
  2840: { CountryCode: "US", type: "Country", displayName: "United States" },
  2854: { CountryCode: "BF", type: "Country", displayName: "Burkina Faso" },
  2858: { CountryCode: "UY", type: "Country", displayName: "Uruguay" },
  2860: { CountryCode: "UZ", type: "Country", displayName: "Uzbekistan" },
  2862: { CountryCode: "VE", type: "Country", displayName: "Venezuela" },
  2876: { CountryCode: "WF", type: "Country", displayName: "Wallis and Futuna" },
  2882: { CountryCode: "WS", type: "Country", displayName: "Samoa" },
  2887: { CountryCode: "YE", type: "Country", displayName: "Yemen" },
  2894: { CountryCode: "ZM", type: "Country", displayName: "Zambia" },

  // --- US STATES (51) — Region = USPS abbreviation, confirmed against Kevel /v1/countries ---
  21132: { CountryCode: "US", Region: "AK", type: "State", displayName: "Alaska" },
  21133: { CountryCode: "US", Region: "AL", type: "State", displayName: "Alabama" },
  21135: { CountryCode: "US", Region: "AR", type: "State", displayName: "Arkansas" },
  21136: { CountryCode: "US", Region: "AZ", type: "State", displayName: "Arizona" },
  21137: { CountryCode: "US", Region: "CA", type: "State", displayName: "California" },
  21138: { CountryCode: "US", Region: "CO", type: "State", displayName: "Colorado" },
  21139: { CountryCode: "US", Region: "CT", type: "State", displayName: "Connecticut" },
  21140: { CountryCode: "US", Region: "DC", type: "State", displayName: "District of Columbia" },
  21141: { CountryCode: "US", Region: "DE", type: "State", displayName: "Delaware" },
  21142: { CountryCode: "US", Region: "FL", type: "State", displayName: "Florida" },
  21143: { CountryCode: "US", Region: "GA", type: "State", displayName: "Georgia" },
  21144: { CountryCode: "US", Region: "HI", type: "State", displayName: "Hawaii" },
  21145: { CountryCode: "US", Region: "IA", type: "State", displayName: "Iowa" },
  21146: { CountryCode: "US", Region: "ID", type: "State", displayName: "Idaho" },
  21147: { CountryCode: "US", Region: "IL", type: "State", displayName: "Illinois" },
  21148: { CountryCode: "US", Region: "IN", type: "State", displayName: "Indiana" },
  21149: { CountryCode: "US", Region: "KS", type: "State", displayName: "Kansas" },
  21150: { CountryCode: "US", Region: "KY", type: "State", displayName: "Kentucky" },
  21151: { CountryCode: "US", Region: "LA", type: "State", displayName: "Louisiana" },
  21152: { CountryCode: "US", Region: "MA", type: "State", displayName: "Massachusetts" },
  21153: { CountryCode: "US", Region: "MD", type: "State", displayName: "Maryland" },
  21154: { CountryCode: "US", Region: "ME", type: "State", displayName: "Maine" },
  21155: { CountryCode: "US", Region: "MI", type: "State", displayName: "Michigan" },
  21156: { CountryCode: "US", Region: "MN", type: "State", displayName: "Minnesota" },
  21157: { CountryCode: "US", Region: "MO", type: "State", displayName: "Missouri" },
  21158: { CountryCode: "US", Region: "MS", type: "State", displayName: "Mississippi" },
  21159: { CountryCode: "US", Region: "MT", type: "State", displayName: "Montana" },
  21160: { CountryCode: "US", Region: "NC", type: "State", displayName: "North Carolina" },
  21161: { CountryCode: "US", Region: "ND", type: "State", displayName: "North Dakota" },
  21162: { CountryCode: "US", Region: "NE", type: "State", displayName: "Nebraska" },
  21163: { CountryCode: "US", Region: "NH", type: "State", displayName: "New Hampshire" },
  21164: { CountryCode: "US", Region: "NJ", type: "State", displayName: "New Jersey" },
  21165: { CountryCode: "US", Region: "NM", type: "State", displayName: "New Mexico" },
  21166: { CountryCode: "US", Region: "NV", type: "State", displayName: "Nevada" },
  21167: { CountryCode: "US", Region: "NY", type: "State", displayName: "New York" },
  21168: { CountryCode: "US", Region: "OH", type: "State", displayName: "Ohio" },
  21169: { CountryCode: "US", Region: "OK", type: "State", displayName: "Oklahoma" },
  21170: { CountryCode: "US", Region: "OR", type: "State", displayName: "Oregon" },
  21171: { CountryCode: "US", Region: "PA", type: "State", displayName: "Pennsylvania" },
  21172: { CountryCode: "US", Region: "RI", type: "State", displayName: "Rhode Island" },
  21173: { CountryCode: "US", Region: "SC", type: "State", displayName: "South Carolina" },
  21174: { CountryCode: "US", Region: "SD", type: "State", displayName: "South Dakota" },
  21175: { CountryCode: "US", Region: "TN", type: "State", displayName: "Tennessee" },
  21176: { CountryCode: "US", Region: "TX", type: "State", displayName: "Texas" },
  21177: { CountryCode: "US", Region: "UT", type: "State", displayName: "Utah" },
  21178: { CountryCode: "US", Region: "VA", type: "State", displayName: "Virginia" },
  21179: { CountryCode: "US", Region: "VT", type: "State", displayName: "Vermont" },
  21180: { CountryCode: "US", Region: "WA", type: "State", displayName: "Washington" },
  21182: { CountryCode: "US", Region: "WI", type: "State", displayName: "Wisconsin" },
  21183: { CountryCode: "US", Region: "WV", type: "State", displayName: "West Virginia" },
  21184: { CountryCode: "US", Region: "WY", type: "State", displayName: "Wyoming" },

  // --- DE STATES (16) — Region = ISO 3166-2:DE without prefix, confirmed against Kevel API ---
  20226: { CountryCode: "DE", Region: "BE", type: "State", displayName: "Berlin" },
  20227: { CountryCode: "DE", Region: "BB", type: "State", displayName: "Brandenburg" },
  20228: { CountryCode: "DE", Region: "BW", type: "State", displayName: "Baden-Wurttemberg" },
  20229: { CountryCode: "DE", Region: "BY", type: "State", displayName: "Bavaria" },
  20230: { CountryCode: "DE", Region: "HB", type: "State", displayName: "Bremen" },
  20231: { CountryCode: "DE", Region: "HE", type: "State", displayName: "Hessen" },
  20232: { CountryCode: "DE", Region: "HH", type: "State", displayName: "Hamburg" },
  20233: { CountryCode: "DE", Region: "MV", type: "State", displayName: "Mecklenburg-Vorpommern" },
  20234: { CountryCode: "DE", Region: "NI", type: "State", displayName: "Lower Saxony" },
  20235: { CountryCode: "DE", Region: "NW", type: "State", displayName: "North Rhine-Westphalia" },
  20236: { CountryCode: "DE", Region: "RP", type: "State", displayName: "Rhineland-Palatinate" },
  20237: { CountryCode: "DE", Region: "SH", type: "State", displayName: "Schleswig-Holstein" },
  20238: { CountryCode: "DE", Region: "SL", type: "State", displayName: "Saarland" },
  20239: { CountryCode: "DE", Region: "SN", type: "State", displayName: "Saxony" },
  20240: { CountryCode: "DE", Region: "ST", type: "State", displayName: "Saxony-Anhalt" },
  20241: { CountryCode: "DE", Region: "TH", type: "State", displayName: "Thuringia" },

  // --- NL PROVINCES (12) — Region = ISO 3166-2:NL without prefix, confirmed against Kevel API ---
  20759: { CountryCode: "NL", Region: "DR", type: "Province", displayName: "Drenthe" },
  20760: { CountryCode: "NL", Region: "FL", type: "Province", displayName: "Flevoland" },
  20761: { CountryCode: "NL", Region: "FR", type: "Province", displayName: "Friesland" },
  20762: { CountryCode: "NL", Region: "GE", type: "Province", displayName: "Gelderland" },
  20763: { CountryCode: "NL", Region: "GR", type: "Province", displayName: "Groningen" },
  20764: { CountryCode: "NL", Region: "LI", type: "Province", displayName: "Limburg" },
  20765: { CountryCode: "NL", Region: "NB", type: "Province", displayName: "North Brabant" },
  20766: { CountryCode: "NL", Region: "NH", type: "Province", displayName: "North Holland" },
  20767: { CountryCode: "NL", Region: "OV", type: "Province", displayName: "Overijssel" },
  20768: { CountryCode: "NL", Region: "UT", type: "Province", displayName: "Utrecht" },
  20769: { CountryCode: "NL", Region: "ZE", type: "Province", displayName: "Zeeland" },
  20770: { CountryCode: "NL", Region: "ZH", type: "Province", displayName: "South Holland" },

  // --- GB PROVINCES (4) — Region confirmed against Kevel API ---
  20339: { CountryCode: "GB", Region: "ENG", type: "Province", displayName: "England" },
  20341: { CountryCode: "GB", Region: "NIR", type: "Province", displayName: "Northern Ireland" },
  20342: { CountryCode: "GB", Region: "SCT", type: "Province", displayName: "Scotland" },
  20343: { CountryCode: "GB", Region: "WLS", type: "Province", displayName: "Wales" },

  // --- CA PROVINCES/TERRITORIES (13) — Region = ISO 3166-2:CA without prefix, confirmed against Kevel API ---
  20113: { CountryCode: "CA", Region: "AB", type: "Province", displayName: "Alberta" },
  20114: { CountryCode: "CA", Region: "BC", type: "Province", displayName: "British Columbia" },
  20115: { CountryCode: "CA", Region: "MB", type: "Province", displayName: "Manitoba" },
  20116: { CountryCode: "CA", Region: "NB", type: "Province", displayName: "New Brunswick" },
  20117: { CountryCode: "CA", Region: "NL", type: "Province", displayName: "Newfoundland and Labrador" },
  20118: { CountryCode: "CA", Region: "NS", type: "Province", displayName: "Nova Scotia" },
  20119: { CountryCode: "CA", Region: "NT", type: "Territory", displayName: "Northwest Territories" },
  20120: { CountryCode: "CA", Region: "NU", type: "Territory", displayName: "Nunavut" },
  20121: { CountryCode: "CA", Region: "ON", type: "Province", displayName: "Ontario" },
  20122: { CountryCode: "CA", Region: "PE", type: "Province", displayName: "Prince Edward Island" },
  20123: { CountryCode: "CA", Region: "QC", type: "Province", displayName: "Quebec" },
  20124: { CountryCode: "CA", Region: "SK", type: "Province", displayName: "Saskatchewan" },
  20125: { CountryCode: "CA", Region: "YT", type: "Territory", displayName: "Yukon" },

  // --- AU STATES (8) — Region confirmed against Kevel API ---
  20034: { CountryCode: "AU", Region: "ACT", type: "State", displayName: "Australian Capital Territory" },
  20035: { CountryCode: "AU", Region: "NSW", type: "State", displayName: "New South Wales" },
  20036: { CountryCode: "AU", Region: "NT",  type: "State", displayName: "Northern Territory" },
  20037: { CountryCode: "AU", Region: "QLD", type: "State", displayName: "Queensland" },
  20038: { CountryCode: "AU", Region: "SA",  type: "State", displayName: "South Australia" },
  20039: { CountryCode: "AU", Region: "TAS", type: "State", displayName: "Tasmania" },
  20040: { CountryCode: "AU", Region: "VIC", type: "State", displayName: "Victoria" },
  20041: { CountryCode: "AU", Region: "WA",  type: "State", displayName: "Western Australia" },
};

module.exports = { GEO_TARGET_MAP };
